=== kyrlouca/Cab-T/CreateInvoicesXML/DhlInvoices.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="invDHL" xmlns="invDHL" elementFormDefault="qualified">
 <xs:simpleType name="String80Type">
  <xs:restriction base="xs:string">
   <xs:maxLength value="80" />
  </xs:restriction>
 </xs:simpleType>
 <xs:complexType name="AddressType">
  <xs:sequence>
   <xs:element name="Address1" type="String80Type" />
   <xs:element name="PostCode" type="String80Type" />
   <xs:element name="City" type="String80Type" />
   <xs:element name="Country" type="String80Type" />
  </xs:sequence>
 </xs:complexType>
 <xs:complexType name="CustomerType">
  <xs:sequence>
   <xs:element name="Name" type="xs:string" />
   <xs:element name="Address" type="AddressType" />
  </xs:sequence>
 </xs:complexType>
 <xs:complexType name="LineType">
  <xs:sequence>
   <xs:element name="Amount" type="xs:decimal" />
   <xs:element name="Category" type="xs:string" />
  </xs:sequence>
 </xs:complexType>
 <xs:complexType name="InvoiceType">
  <xs:sequence>
   <xs:element name="SerialNumber" type="xs:int" />
   <xs:element name="HawbId" type="xs:string" />
   <xs:element name="MawbId" type="xs:string" />
   <xs:element name="District" type="xs:string" />
   <xs:element name="InvoiceDate" type="xs:date" />
   <xs:element name="Amount" type="xs:decimal" />
   <xs:element name="Customer" type="CustomerType" />
   <xs:element name="Lines">
    <xs:complexType>
     <xs:choice>
      <xs:element name="Line" type="LineType" minOccurs="1" maxOccurs="unbounded" />
     </xs:choice>
    </xs:complexType>
   </xs:element>
  </xs:sequence>
 </xs:complexType>
 <xs:element name="CypDhl">
  <xs:complexType>
   <xs:sequence>
    <xs:element name="Hdr">
     <xs:complexType>
      <xs:sequence>
       <xs:element name="Origin" type="xs:string" />
       <xs:element name="FileCreationDate" type="xs:date" />
       <xs:element name="FileName" type="xs:string" />
      </xs:sequence>
     </xs:complexType>
    </xs:element>
    <xs:element name="Invoices">
     <xs:complexType>
      <xs:choice>
       <xs:element name="Invoice" type="InvoiceType" minOccurs="1" maxOccurs="unbounded" />
      </xs:choice>
     </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
</xs:schema>

=== kyrlouca/Cab-T/CreateInvoicesXML/dhlCypInv_1_1_20170801111653.XML
<?xml version="1.0" encoding="UTF-8"?>
<CypDhl xmlns="invDHL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="invDHL DhlInvoices.xsd"><Hdr xmlns=""><Origin>From DHL Cyprus</Origin><FileCreationDate>2017-08-01</FileCreationDate><FileName>C:\Data\DelphiProjects\Tariffs\InvoiceXML\dhlCypInv_1_1_20170801111653.XML</FileName></Hdr><Invoices xmlns=""><Invoice><SerialNumber>1</SerialNumber><HawbId>2011452074</HawbId><MawbId>61591381611</MawbId><District></District><InvoiceDate>2017-07-30</InvoiceDate><Amount>   0.00 </Amount><Customer><Name>DROUSKO HOUSE AGENCIES LTD</Name><Address><Address1></Address1><PostCode></PostCode><City></City><Country></Country></Address></Customer><Lines><Line><Amount>   0.00 </Amount><Category>GVAT</Category></Line></Lines></Invoice></Invoices></CypDhl>

=== kyrlouca/Cab-T/CreateInvoicesXML/dhlCypInv_2_2_20170801112502.XML
<?xml version="1.0" encoding="UTF-8"?>
<CypDhl xmlns="invDHL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="invDHL DhlInvoices.xsd"><Hdr><Origin>From DHL Cyprus</Origin><FileCreationDate>2017-08-01</FileCreationDate><FileName>C:\Data\DelphiProjects\Tariffs\InvoiceXML\dhlCypInv_2_2_20170801112502.XML</FileName></Hdr><Invoices><Invoice><SerialNumber>2</SerialNumber><HawbId>2370129075</HawbId><MawbId>61591381611</MawbId><District>LAR</District><InvoiceDate>2017-07-30</InvoiceDate><Amount>   3.50 </Amount><Customer><Name> ANDREAS   ACHILLEOS</Name><Address><Address1>7 AGIOU THERAPONTOS</Address1><PostCode>NICOSIA </PostCode><City>CYPRUS</City><Country>CYPRUS</Country></Address></Customer><Lines><Line><Amount>   3.50 </Amount><Category>GCUS</Category></Line><Line><Amount>   0.00 </Amount><Category>GDHL</Category></Line><Line><Amount>   0.00 </Amount><Category>GVAT</Category></Line></Lines></Invoice></Invoices></CypDhl>

=== kyrlouca/Cab-T/CreateInvoicesXML/dhlCypInv_8_10_20170801133429.XML
<?xml version="1.0" encoding="UTF-8"?>
<CypDhl xmlns="invDHL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="invDHL DhlInvoices.xsd">
	<Hdr>
		<Origin>From DHL Cyprus</Origin>
		<FileCreationDate>2017-08-01</FileCreationDate>
		<FileName>C:\Data\DelphiProjects\Tariffs\InvoiceXML\dhlCypInv_8_10_20170801133429.XML</FileName>
	</Hdr>
	<Invoices>
		<Invoice>
			<SerialNumber>8</SerialNumber>
			<HawbId>2532919185</HawbId>
			<MawbId>61591381611</MawbId>
			<District>NIC</District>
			<InvoiceDate>2017-08-01</InvoiceDate>
			<Amount> 851.13 </Amount>
			<Customer>
				<Name>UDJAT EYE FASHIONS LTD</Name>
				<Address>
					<Address1>KLEOSTHENOUS</Address1>
					<PostCode>2012</PostCode>
					<City>NICOSIA</City>
					<Country>CYPRUS</Country>
				</Address>
			</Customer>
			<Lines>
				<Line>
					<Amount>   3.50 </Amount>
					<Category>GCUS</Category>
				</Line>
				<Line>
					<Amount>   0.00 </Amount>
					<Category>GDHL</Category>
				</Line>
				<Line>
					<Amount>   0.00 </Amount>
					<Category>GEXC</Category>
				</Line>
				<Line>
					<Amount>   0.00 </Amount>
					<Category>GIMP</Category>
				</Line>
				<Line>
					<Amount> 847.63 </Amount>
					<Category>GVAT</Category>
				</Line>
			</Lines>
		</Invoice>
		<Invoice>
			<SerialNumber>9</SerialNumber>
			<HawbId>2819013945</HawbId>
			<MawbId>61591381611</MawbId>
			<District>NIC</District>
			<InvoiceDate>2017-08-01</InvoiceDate>
			<Amount>  17.00 </Amount>
			<Customer>
				<Name>THE  ENGLISH  SCHOOL</Name>
				<Address>
					<Address1>ATHALASSAS 3</Address1>
					<PostCode>3022</PostCode>
					<City>STROVOLOS</City>
					<Country>CYPRUS</Country>
				</Address>
			</Customer>
			<Lines>
				<Line>
					<Amount>   2.00 </Amount>
					<Category>GCUS</Category>
				</Line>
				<Line>
					<Amount>  15.00 </Amount>
					<Category>GVAT</Category>
				</Line>
			</Lines>
		</Invoice>
		<Invoice>
			<SerialNumber>10</SerialNumber>
			<HawbId>2370129075</HawbId>
			<MawbId>61591381611</MawbId>
			<District>LAR</District>
			<InvoiceDate>2017-08-01</InvoiceDate>
			<Amount>   9.37 </Amount>
			<Customer>
				<Name> ANDREAS   ACHILLEOS</Name>
				<Address>
					<Address1>7 AGIOU THERAPONTOS</Address1>
					<PostCode>NICOSIA </PostCode>
					<City>CYPRUS</City>
					<Country>CYPRUS</Country>
				</Address>
			</Customer>
			<Lines>
				<Line>
					<Amount>   3.50 </Amount>
					<Category>GCUS</Category>
				</Line>
				<Line>
					<Amount>   0.00 </Amount>
					<Category>GDHL</Category>
				</Line>
				<Line>
					<Amount>   0.00 </Amount>
					<Category>GEXC</Category>
				</Line>
				<Line>
					<Amount>   1.48 </Amount>
					<Category>GIMP</Category>
				</Line>
				<Line>
					<Amount>   4.39 </Amount>
					<Category>GVAT</Category>
				</Line>
			</Lines>
		</Invoice>
	</Invoices>
</CypDhl>

=== kyrlouca/Cab-T/CreateInvoicesXML/dhlCypInv_3_4_20170801095553.XML
<?xml version="1.0" encoding="UTF-8"?>
<CypDhl xmlns="invDHL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="invDHL DhlInvoices.xsd"><Hdr xmlns=""><Origin>From DHL Cyprus</Origin><FileCreationDate>2017-08-01</FileCreationDate><FileName>C:\Data\DelphiProjects\Tariffs\InvoiceXML\dhlCypInv_3_4_20170801095553.XML</FileName></Hdr><Invoices xmlns=""><Invoice><SerialNumber>3</SerialNumber><HawbId>2532919185</HawbId><MawbId>61591381611</MawbId><District>NIC</District><InvoiceDate>2017-07-30</InvoiceDate><Amount>   3.50 </Amount><Customer><Name>UDJAT EYE FASHIONS LTD</Name><Address><Address1>NICOSIA</Address1><PostCode></PostCode><City></City><Country>CYPRUS</Country></Address></Customer><Lines><Line><Amount>   3.50 </Amount><Category>GCUS</Category></Line><Line><Amount>   0.00 </Amount><Category>GDHL</Category></Line><Line><Amount>   0.00 </Amount><Category>GVAT</Category></Line></Lines></Invoice><Invoice><SerialNumber>4</SerialNumber><HawbId>2819013945</HawbId><MawbId>61591381611</MawbId><District>NIC</District><InvoiceDate>2017-07-30</InvoiceDate><Amount>  17.00 </Amount><Customer><Name>THE  ENGLISH  SCHOOL</Name><Address><Address1>NICOSIA</Address1><PostCode></PostCode><City></City><Country>CYPRUS</Country></Address></Customer><Lines><Line><Amount>   2.00 </Amount><Category>GCUS</Category></Line><Line><Amount>  15.00 </Amount><Category>GVAT</Category></Line></Lines></Invoice></Invoices></CypDhl>

=== kyrlouca/Cab-T/CreateInvoicesXML/dhlCypInv_11_11_20170802182011.XML
<?xml version="1.0" encoding="UTF-8"?>
<CypDhl xmlns="invDHL" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="invDHL DhlInvoices.xsd">
	<Hdr>
		<Origin>From DHL Cyprus</Origin>
		<FileCreationDate>2017-08-02</FileCreationDate>
		<FileName>C:\Data\DelphiProjects\TokyoCabT\InvoiceXML\dhlCypInv_11_11_20170802182011.XML</FileName>
	</Hdr>
	<Invoices>
		<Invoice>
			<SerialNumber>11</SerialNumber>
			<HawbId>2011452074</HawbId>
			<MawbId>61591381611</MawbId>
			<District>NIC</District>
			<InvoiceDate>2017-08-01</InvoiceDate>
			<Amount>   3.67 </Amount>
			<Customer>
				<Name> ANGELIKA KYRIAKOU</Name>
				<Address>
					<Address1>DEMONICOU 8</Address1>
					<PostCode>NICOSIA </PostCode>
					<City>CYPRUS</City>
					<Country>CYPRUS</Country>
				</Address>
			</Customer>
			<Lines>
				<Line>
					<Amount>   3.50 </Amount>
					<Category>GCUS</Category>
				</Line>
				<Line>
					<Amount>   0.00 </Amount>
					<Category>GDHL</Category>
				</Line>
				<Line>
					<Amount>   0.00 </Amount>
					<Category>GEXC</Category>
				</Line>
				<Line>
					<Amount>   0.02 </Amount>
					<Category>GIMP</Category>
				</Line>
				<Line>
					<Amount>   0.15 </Amount>
					<Category>GVAT</Category>
				</Line>
			</Lines>
		</Invoice>
	</Invoices>
</CypDhl>
